#!/bin/bash
# generated by tools/build-roots-cache.sh — do not edit; regenerate after registry changes
#
# Emits .claude/roots.cache: one absolute PHYSICAL directory per line.
# Sources: every `path:` in PROJECT_REGISTRY.yaml + this bennu repo root.
# This is the ONLY place that parses YAML; hooks read the cache, never the registry.
# Per path: expand leading ~; if it EXISTS resolve to its physical realpath,
# else keep the tilde-expanded absolute as-is and emit a `# WARN missing:` line.
# Trailing slashes stripped; output deduped after resolution.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
registry="$repo_root/PROJECT_REGISTRY.yaml"
out="$repo_root/.claude/roots.cache"

if [ ! -f "$registry" ]; then
  echo "build-roots-cache: registry not found: $registry" >&2
  exit 1
fi

# Collect raw paths: registry `path:` values + fixed extras.
raw="$(
  # Grab `path:` values (strip quotes); tolerate leading whitespace.
  grep -E '^[[:space:]]*path:[[:space:]]*' "$registry" \
    | sed -E 's/^[[:space:]]*path:[[:space:]]*//; s/^"//; s/"$//'
  # The bennu repo root itself (this checkout).
  echo "$repo_root"
)"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

printf '%s\n' "$raw" | while IFS= read -r p; do
  [ -n "$p" ] || continue
  # Expand a leading ~ to $HOME.
  case "$p" in
    "~") p="$HOME" ;;
    "~/"*) p="$HOME/${p#\~/}" ;;
  esac
  # Strip trailing slashes (keep root "/").
  while [ "$p" != "/" ] && [ "${p%/}" != "$p" ]; do p="${p%/}"; done
  if [ -d "$p" ]; then
    rp="$(python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$p")"
    rp="${rp%/}"
    [ -n "$rp" ] || rp="/"
    printf '%s\n' "$rp" >> "$tmp"
  else
    printf '# WARN missing: %s\n' "$p" >> "$tmp"
    printf '%s\n' "$p" >> "$tmp"
  fi
done

{
  printf '# generated by tools/build-roots-cache.sh — do not edit; regenerate after registry changes\n'
  sort -u "$tmp"
} > "$out"

echo "build-roots-cache: wrote $out"
